version: "3"
services:
  mongo-app:
    container_name: mongo-app
    image: mongo-app
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - db
  db:
    container_name: db
    image: mongo
    ports:
      - '27019:27017'